### PR TITLE
Python 2-3 compatibility

### PR DESCRIPTION
**Pull request by ceLoFaN**
I took the liberty to extend on @mattgallivan's work a bit.

I renamed the package to eventregistry (lowercase) as the PEP8 style guide suggests: https://www.python.org/dev/peps/pep-0008/#package-and-module-names . This also fixed this guy's problem https://github.com/gregorleban/EventRegistry/issues/2#issuecomment-169318055

I also tidied up imports here and there, and used relative imports where needed because I was getting some imports errors. I assume you set up some pythonpaths for your project to get it working before.

I want to point out that the project has 10 tests out of 40 failing, which haven't changed with this PR (except for the error message in some cases, but the tests that fail are the same).

### CODE REVIEW

**Comment by gregorleban** [comment]
Hi @ceLoFaN:
thank you very much for your changes - it seems you've done some very nice work. I'll have a look and merge your code. Does it keep the compatibility with the python 2.x?

**Comment by ceLoFaN** [comment]
Yes, the code should be backwards compatible with python2.x. I used PyCharm's code inspection for the compatibility check. There were some unused imports of urllib2 that wouldn't work in Python3.5, but other than that, @mattgallivan did a good job.

**Comment by mattgallivan** [comment]
@ceLoFaN Cheers (and thanks for cleaning up my mess :D)!

**Comment by gregorleban** [comment]
@ceLoFaN : please don't give up on me :) I will definitely merge your pull request soon - I'm currently finishing a big backend update and I need another week or two to make the new release. After that I'll definitely check your pull request and merge it if it doesn't break the python 2.x compatibility. sorry again for this delay.

**Comment by gregorleban** [comment]
@ceLoFaN : thanks again for the code changes. I've just merged your changes to master

**Comment by grantgumina** [comment]
Does EventRegistry work out of the box with Python 3 or is there a specific version I need to install? After doing "pip3 install eventregistry", I'm encountering issues running any script that includes EventRegistry. I've been able to run 2to3 on the files and resolve them, however I'm wondering if there's something I'm missing here.

**Comment by gregorleban** [comment]
Hi,

the module should work out of the box with Python 2.x and 3.x. The error that you are mentioning above I think has nothing to do with python versions but with the input parameters that you provide which are not handled properly. Could you send me the script that you are testing on my email gleban AT gmail.com so that I check if that encoding is the only thing that needs modifications?

**Comment by grantgumina** [comment]
I've been playing around with it some more assuming that I messed something up when running the 2to3 tool. However, after a clean install, I cannot run any script which includes the EventRegistry module without encountering an ImportError. I've gone ahead and opened another issue here describing the issue in more detail. 

New issue: #22

**Pull request closed without merging**
